name: CI
on:
  push:
    branches:
     - master
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
          node-version: 18
          cache: 'npm'

     - name: Install dependencies
       run: npm ci

     - name: Build project
       run: npm run build

     - name: Archive production artifacts
       run: |
        mkdir -p release
        cp -r dist/* release/
       shell: bash

     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
        name: release-artifact
        path: release/

     - name: Upload artifact (node_modules)
       uses: actions/upload-artifact@v4
       with:
        name: node-modules-artifact
        path: node_modules
  
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > pennsylvania-sam-mbp.pem
          chmod 600 pennsylvania-sam-mbp.pem

      - name: Ensure SSH Directory Exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
      
      - name: Add Server to Known Hosts
        run: |
          ssh-keyscan -H ec2-18-226-104-112.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH into Server and List Files
        run: ssh -i "pennsylvania-sam-mbp.pem" ubuntu@ec2-18-226-104-112.us-east-2.compute.amazonaws.com "ls -lah"

      - name: Create target directory on server
        run: |
          ssh -i "pennsylvania-sam-mbp.pem" ubuntu@ec2-18-226-104-112.us-east-2.compute.amazonaws.com "mkdir -p /home/ubuntu/app2/foo"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: release-artifact
          path: release/

      - name: Download node-modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules-artifact
          path: node_modules

      - name: Copy Code to Server
        run: |
          scp -i "pennsylvania-sam-mbp.pem" -r release/* ubuntu@ec2-18-226-104-112.us-east-2.compute.amazonaws.com:/home/ubuntu/app2/
          scp -i "pennsylvania-sam-mbp.pem" -r node_modules ubuntu@ec2-18-226-104-112.us-east-2.compute.amazonaws.com:/home/ubuntu/app2/

          